sudo: false

language: node_js

node_js:
  - "8"

notifications:
  disabled: true

before_install:
  - npm install -g npm@5

install:
  - npm install

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - DEBUG="-babel,*" npm test
